
# Reset password
PATCH http://localhost:3000/api/v1/users/resetPassword/446762c305ea308a3dd31ffb2be95ea8ca92cf262f192d6013963002df7b5e20 HTTP/1.1
Content-Type: application/json

{
    "password":"newpass3",
    "passwordConfirm":"newpass3"
}

###

# Update loged user password
PATCH http://localhost:3000/api/v1/users/updateMyPassword HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZWI1MzgxMDgwZWRlNDEwYzY3NGQ4MiIsImlhdCI6MTY3NjU0MjcxNiwiZXhwIjoxNjg0MzE4NzE2fQ.3C4o4zwkmvqWR5Hnf5BJbsGlIaDGn8xvHbu3nVrKP10

{
    "passwordCurrent":"newpass3",
    "password":"newpass5",
    "passwordConfirm":"newpass5"
}

###


# Login request
POST http://localhost:3000/api/v1/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "bemarivo_admin@gmail.com",
    "password": "12345678"
}
###

# Signup requeste
 POST http://localhost:3000/api/v1/users/signup HTTP/1.1
Content-Type: application/json

{
    "name": "BEMA_rivo",
    "email": "bemarivo1@gmail.com",
    "password": "12345678",
    "passwordConfirm": "12345678"
}
###

# Forgot Password
POST http://localhost:3000/api/v1/users/forgotPassword HTTP/1.1
Content-Type: application/json

{
    "name": "BEMA",
    "lasteName": "Zirika",
    "email": "ramamps33@gmail.com"
}

###
