# Get request get all tours
GET http://localhost:3000/api/v1/tours HTTP/1.1

###

# Get request get one tour 
# The id of the tour must be less than 5
GET http://localhost:3000/api/v1/tours/63d29710bfc87c3f0c7c3d0c HTTP/1.1

###

# Update tour
# The id of the tour must be less than 5
PATCH http://localhost:3000/api/v1/tours/63d279e87177b6250d898f2e HTTP/1.1
content-type: application/json

{
    "name" : "tour 001",
    "description": "This is tour 003",
    "imageCover" : "Mountain",
}

###

# Delete tour
# The id of the tour must be less than 5
DELETE http://localhost:3000/api/v1/tours/63d29710bfc87c3f0c7c3d0c HTTP/1.1

###

# Post request create tours
POST http://localhost:3000/api/v1/tours HTTP/1.1
content-type: application/json

{
    "name" : "tour 001",
    "description": "This is tour 001",
    "duration" : 5000,
    "imageCover" : "Mountain"
}
###