# Get request get all tours
GET http://localhost:3000/api/v1/tours HTTP/1.1
###

#   Get request all tours with filtre
GET http://localhost:3000/api/v1/tours/?imageCover=Image 1&page=2 HTTP/1.1
###

#   Get request all tours with pagination
GET http://localhost:3000/api/v1/tours?page=2&limit=2 HTTP/1.1
###


# Get monthly plan
GET http://localhost:3000/api/v1/tours/monthly-plan/2021 HTTP/1.1
###


# Get tour stats request
GET http://localhost:3000/api/v1/tours/tour-stats HTTP/1.1
###

# Get tour top five
GET http://localhost:3000/api/v1/tours/top-5-cheaps HTTP/1.1
###

# Get request all tours with sorting ascending order
GET http://localhost:3000/api/v1/tours?sort=duration HTTP/1.1
###

# Get request all tours with sorting descanding order
GET http://localhost:3000/api/v1/tours?sort=-duration HTTP/1.1
###

# Get request all tours with sorting with second parameter
GET http://localhost:3000/api/v1/tours?sort=duration.price HTTP/1.1
###

# Get request all tours with Field limiting
GET http://localhost:3000/api/v1/tours?fields=name.description.duration HTTP/1.1
###

# Get request all tours with Field limiting
GET http://localhost:3000/api/v1/tours?fields HTTP/1.1
###

#   Get request all tours with advanced filtering
GET http://localhost:3000/api/v1/tours/?imageCover=Image 1&page=2&duration[gte]=4000 HTTP/1.1
###


# Get request get one tour 
# The id of the tour must be less than 5
GET http://localhost:3000/api/v1/tours/63d29710bfc87c3f0c7c3d0c HTTP/1.1

###

# Update tour
# The id of the tour must be less than 5
PATCH http://localhost:3000/api/v1/tours/63d279e87177b6250d898f2e HTTP/1.1
content-type: application/json

{
    "name" : "tour 001",
    "description": "This is tour 003",
    "imageCover" : "Mountain",
}

###

# Delete tour
# The id of the tour must be less than 5
DELETE http://localhost:3000/api/v1/tours/63d29710bfc87c3f0c7c3d0c HTTP/1.1

###

# Post request create tours
POST http://localhost:3000/api/v1/tours HTTP/1.1
content-type: application/json

{
    "name": "Secrete test dfsfs",
    "description": "this is secrete tour",
    "duration": 3,
    "imageCover": "Image 4",
    "price": 2,
    "ratingAverage" : 10
}
###