# Get request get all tours
GET http://localhost:3000/api/v1/tours HTTP/1.1

###

# Get request get one tour 
# The id of the tour must be less than 5
GET http://localhost:3000/api/v1/tours/3 HTTP/1.1

###

# Update tour
# The id of the tour must be less than 5
PATCH http://localhost:3000/api/v1/tours/3 HTTP/1.1
content-type: application/json

{
    "name" : "tour 03",
    "description": "this is tour 003"
}

###

# Delete tour
# The id of the tour must be less than 5
DELETE http://localhost:3000/api/v1/tours/4 HTTP/1.1

###

# Post request create tours
POST http://localhost:3000/api/v1/tours HTTP/1.1
content-type: application/json

{
    "name": "tour 5",
    "description": "this is tour 5"
}
###